### ISSUE TITLE
同一主机启动多个proxy报错

### ISSUE THREAD

**Issue by tyyzqmf** [dora-js/dora-plugin-proxy#118]
npm info it worked if it ends with ok
npm info using npm@4.1.2
npm info using node@v7.7.0
npm info lifecycle @~prestart: @
npm info lifecycle @~start: @

> @ start /schemaui
> dora -p 8901 --plugins "webpack,proxy?port=8988,browser-history?index=/src/entries/index.html"

          proxy: load rule from proxy.config.js
(node:23) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
          proxy: listened on 8988
temp certs cleared
Generating RSA private key, 2048 bit long modulus
Caught exception: Error: watch /schemaui/package.json EMFILE
    at exports._errnoException (util.js:1029:11)
    at FSWatcher.start (fs.js:1399:19)
    at Object.fs.watch (fs.js:1425:11)
    at createFsWatchInstance (/schemaui/node_modules/.1.6.1@chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/schemaui/node_modules/.1.6.1@chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/schemaui/node_modules/.1.6.1@chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/schemaui/node_modules/.1.6.1@chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/schemaui/node_modules/.1.6.1@chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:114:15)
AnyProxy is about to exit with code: 0
............npm info lifecycle @~poststart: @
....npm info ok 
+++
..

**Comment by tyyzqmf** [comment]
(node:23) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
怎么修改这个端口23？按道理是随机的吧？但是我发现启动两个都是23
