### ISSUE TITLE
Is res providing a subset of Express' API as mentioned?

### ISSUE THREAD

**Issue by dxps** [dora-js/dora-plugin-proxy#89]
Hello,

While playing with `antd-init` result and trying to proxy the requests to static assets, the following rule was included in proxy.config.js file:

``` javascript
  '/assets/*': function(req, res) {

    var options = {
      root: __dirname,
      dotfiles: 'deny',
      headers: {
        'x-timestamp': Date.now(),
        'x-sent': true
      }
    };
    var fileName = req.params[0];
    res.sendFile(fileName, options, function (err) {
      if (err) {
        console.log(err);
        res.status(err.status).end();
      }
      else {
        console.log('Sent:', fileName);
      }
    });
  },
```

The [README](https://github.com/dora-js/dora-plugin-proxy) includes an example of using custom functions which refers to [Express API](http://expressjs.com/en/api.html).
The custom function listed above is using [res.sendFile()](http://expressjs.com/en/api.html#res.sendFile) method. However, a request to 
[/assets/images/favicon.png](http://127.0.0.1:8989/assets/images/favicon.png) crashes the node engine with the following error:

``` bash
> npm start

> @ start /files/dev/react/ant-demo
> dora -p 8001 --plugins "webpack,hmr,proxy,livereload?enableJs=false&injectHost=127.0.0.1,browser-history?index=/src/entries/index.html"

          proxy: load rule from proxy.config.js
          proxy: listened on 8989
     livereload: listening on 35729
📦  538/538 build modules
webpack: bundle build is now finished.

          proxy: GET /assets/images/favicon.png matches /assets/*, respond with custom function
Caught exception: TypeError: res.sendFile is not a function
    at module.exports./assets/* (/files/dev/react/ant-demo/proxy.config.js:46:9)
    at /files/dev/react/ant-demo/node_modules/dora-plugin-proxy/lib/rule.js:52:11
    at batchMatch (/files/dev/react/ant-demo/node_modules/dora-plugin-proxy/lib/rule.js:174:22)
    at Object.dealLocalResponse (/files/dev/react/ant-demo/node_modules/dora-plugin-proxy/lib/rule.js:37:14)
    at dealWithLocalResponse (/files/dev/react/ant-demo/node_modules/dora-anyproxy/lib/requestHandler.js:94:18)
    at routeReq (/files/dev/react/ant-demo/node_modules/dora-anyproxy/lib/requestHandler.js:86:13)
    at /files/dev/react/ant-demo/node_modules/dora-anyproxy/node_modules/async/lib/async.js:607:21
    at /files/dev/react/ant-demo/node_modules/dora-anyproxy/node_modules/async/lib/async.js:246:17
    at iterate (/files/dev/react/ant-demo/node_modules/dora-anyproxy/node_modules/async/lib/async.js:146:13)
    at /files/dev/react/ant-demo/node_modules/dora-anyproxy/node_modules/async/lib/async.js:157:25
AnyProxy is about to exit with code: 0
> 
```

Only the following methods are provided for `res`?
1. set(object|key, value)
2. type(json|html|text|png|...)
3. status(200|404|304)
4. json(jsonData)
5. jsonp(jsonData[, callbackQueryName])
6. end(string|object)

If yes, what option should I have for the purpose of serving static files directly from such setup, without proxy-ing to other http endpoints, such as an Express instance specifically made for this?

Thanks.

**Comment by sorrycc** [comment]
You don't need to proxy `/assets/*`, proxy server will fall back to dora server (port 8001), it serves the static file.

**Comment by dxps** [comment]
You're absolutely right. Thank you! 😄
